### ISSUE TITLE
build script

### ISSUE THREAD

**Issue by and-ri** [pkgxdev/brewkit#166]
Hello! Do you think it is possible to somehow modify the build and test script so that it does this in other directories? I mean `pkg build` to build for example in `~/.teabuild/...` and then move it to `~/.tea`
This would make it easier to track portability issues locally.

**Comment by jhheider** [comment]
You could certainly do this via `TEA_PREFIX`. You'd just need `tea.xyz` installed there (and possibly `tea.xyz/brewkit`

**Comment by mxcl** [comment]
I have tried to implement this a few times.

1. it should be opt-in so that casual contributors aren't put off by relocation issues and instead submit the PR *and then find out there are relocation issues*, we can then help them fix it.
2. so add an option to do this. easiest way to achieve what we want is by renaming the pkg eg. foo.com -> _foo.com and then moving the installed prefix at the end to the original name
